management:
  endpoints:
    web:
      exposure:
        include: none
spring:
  application:
    name: tigor-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: dgs-service
#              uri: http://dgs-service
#              predicates:
#                - Path=/graphql/**
  datasource:
    url: jdbc:mariadb://mariadb:3306/tigor?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: tigor
    password: NmDwA_`q
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  security:
    enable-authentication: false
#  security:
#    user:
#      name: admin
#      password: 19547047
#      roles: ACTUATOR, ADMIN
server:
  port: 8008
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/

logging:
  level:
    org.springframework.boot.actuate.autoconfigure: DEBUG