management:
  endpoints:
    web:
      exposure:
        include: none
spring:
  application:
    name: tigor-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: dgs-service
#              uri: http://dgs-service
#              predicates:
#                - Path=/graphql/**
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/tigor
    username: tigor
    password: tigor
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  security:
    enable-authentication: false
#  security:
#    user:
#      name: admin
#      password: 19547047
#      roles: ACTUATOR, ADMIN
server:
  port: 8008
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/

logging:
  level:
    org.springframework.boot.actuate.autoconfigure: DEBUG