
spring:
  application:
    name: tigor-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: dgs-service
              uri: http://dgs-service
              predicates:
                - Path=/graphql/**
server:
  port: 8008
